sonar.projectKey=egecetin_libKaleidoscope
sonar.organization=egecetin

sonar.projectName=libKaleidoscope
sonar.sources=src,include
sonar.tests=tests,python/python-tests.py
sonar.exclusions=thirdparty/**,tests/check/**,tests/gtest/**
sonar.test.exclusions=tests/check/**,tests/gtest/**
