[files]
extend-exclude = [
                    "build/",
                    "cmake/",
                    "thirdparty/",
                    "tests/data/",
                    "codespell-ignore-list.txt"
                 ]

[default.extend-identifiers]


[default.extend-words]
Ege="Ege"

[type.make]
extend-glob = []
check-file = false
