var searchData=
[
  ['simple_203_20step_20api_20strong_0',['🎪 &lt;strong&gt;Simple 3-Step API&lt;/strong&gt;',['../index.html#autotoc_md16',1,'']]],
  ['slicetriangle_1',['slicetriangle',['../kaleidoscope_8c.html#af4d2cb7fd0363406ec3b4e4b7d8692c4',1,'sliceTriangle(TransformationInfo *transformPtr, int width, int height, int n, double scaleDown):&#160;kaleidoscope.c'],['../kaleidoscope_8h.html#af4d2cb7fd0363406ec3b4e4b7d8692c4',1,'sliceTriangle(TransformationInfo *transformPtr, int width, int height, int n, double scaleDown):&#160;kaleidoscope.c']]],
  ['source_20strong_2',['🛠️ &lt;strong&gt;Building from Source&lt;/strong&gt;',['../index.html#autotoc_md13',1,'']]],
  ['srclocation_3',['srcLocation',['../structTransformationInfo__t.html#ac337974d113d7a2294e0c3c7bdf46db8',1,'TransformationInfo_t']]],
  ['srcoffset_4',['srcOffset',['../structTransformationInfo__t.html#a2a85246bd5dc74432320d0a898ff8bf5',1,'TransformationInfo_t']]],
  ['stack_20strong_5',['🛠️ &lt;strong&gt;Technology Stack&lt;/strong&gt;',['../index.html#autotoc_md2',1,'']]],
  ['star_20this_20repo_20if_20you_20found_20it_20useful_20strong_20🌟_6',['🌟 &lt;strong&gt;Star this repo if you found it useful!&lt;/strong&gt; 🌟',['../index.html#autotoc_md30',1,'']]],
  ['status_20strong_7',['📊 &lt;strong&gt;Project Status&lt;/strong&gt;',['../index.html#autotoc_md1',1,'']]],
  ['step_20api_20strong_8',['🎪 &lt;strong&gt;Simple 3-Step API&lt;/strong&gt;',['../index.html#autotoc_md16',1,'']]],
  ['strong_20benchmark_20your_20system_20strong_9',['🏃‍♂️ &lt;strong&gt;Benchmark Your System&lt;/strong&gt;',['../index.html#autotoc_md25',1,'']]],
  ['strong_20building_20from_20source_20strong_10',['🛠️ &lt;strong&gt;Building from Source&lt;/strong&gt;',['../index.html#autotoc_md13',1,'']]],
  ['strong_20command_20line_20magic_20strong_11',['🖥️ &lt;strong&gt;Command Line Magic&lt;/strong&gt;',['../index.html#autotoc_md17',1,'']]],
  ['strong_20contributing_20strong_12',['🤝 &lt;strong&gt;Contributing&lt;/strong&gt;',['../index.html#autotoc_md27',1,'']]],
  ['strong_20core_20languages_20strong_13',['🎯 &lt;strong&gt;Core Languages&lt;/strong&gt;',['../index.html#autotoc_md8',1,'']]],
  ['strong_20key_20features_20strong_14',['🌟 &lt;strong&gt;Key Features&lt;/strong&gt;',['../index.html#autotoc_md5',1,'']]],
  ['strong_20license_20strong_15',['📄 &lt;strong&gt;License&lt;/strong&gt;',['../index.html#autotoc_md28',1,'']]],
  ['strong_20lightning_20fast_20performance_20strong_16',['⚡ &lt;strong&gt;Lightning Fast Performance&lt;/strong&gt;',['../index.html#autotoc_md23',1,'']]],
  ['strong_20performance_20benchmarks_20strong_17',['🚀 &lt;strong&gt;Performance Benchmarks&lt;/strong&gt;',['../index.html#autotoc_md22',1,'']]],
  ['strong_20performance_20visualization_20strong_18',['📈 &lt;strong&gt;Performance Visualization&lt;/strong&gt;',['../index.html#autotoc_md24',1,'']]],
  ['strong_20programming_20language_20examples_20strong_19',['💻 &lt;strong&gt;Programming Language Examples&lt;/strong&gt;',['../index.html#autotoc_md20',1,'']]],
  ['strong_20project_20status_20strong_20',['📊 &lt;strong&gt;Project Status&lt;/strong&gt;',['../index.html#autotoc_md1',1,'']]],
  ['strong_20python_20users_20recommended_20strong_21',['🐍 &lt;strong&gt;Python Users (Recommended)&lt;/strong&gt;',['../index.html#autotoc_md11',1,'']]],
  ['strong_20quick_20installation_20strong_22',['📦 &lt;strong&gt;Quick Installation&lt;/strong&gt;',['../index.html#autotoc_md10',1,'']]],
  ['strong_20simple_203_20step_20api_20strong_23',['🎪 &lt;strong&gt;Simple 3-Step API&lt;/strong&gt;',['../index.html#autotoc_md16',1,'']]],
  ['strong_20star_20this_20repo_20if_20you_20found_20it_20useful_20strong_20🌟_24',['🌟 &lt;strong&gt;Star this repo if you found it useful!&lt;/strong&gt; 🌟',['../index.html#autotoc_md30',1,'']]],
  ['strong_20supported_20languages_20strong_25',['🎭 &lt;strong&gt;Supported Languages&lt;/strong&gt;',['../index.html#autotoc_md7',1,'']]],
  ['strong_20technology_20stack_20strong_26',['🛠️ &lt;strong&gt;Technology Stack&lt;/strong&gt;',['../index.html#autotoc_md2',1,'']]],
  ['strong_20usage_20guide_20strong_27',['🎯 &lt;strong&gt;Usage Guide&lt;/strong&gt;',['../index.html#autotoc_md15',1,'']]],
  ['strong_20visual_20example_20strong_28',['🎨 &lt;strong&gt;Visual Example&lt;/strong&gt;',['../index.html#autotoc_md18',1,'']]],
  ['strong_20what_20is_20libkaleidoscope_20strong_29',['🎯 &lt;strong&gt;What is LibKaleidoscope?&lt;/strong&gt;',['../index.html#autotoc_md4',1,'']]],
  ['supported_20languages_20strong_30',['🎭 &lt;strong&gt;Supported Languages&lt;/strong&gt;',['../index.html#autotoc_md7',1,'']]],
  ['system_20strong_31',['🏃‍♂️ &lt;strong&gt;Benchmark Your System&lt;/strong&gt;',['../index.html#autotoc_md25',1,'']]]
];
