name: "Coverage"
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Prepare system
        run: |
          sudo apt update
          sudo apt install gcovr -y
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DKALEIDOSCOPE_ENABLE_TESTS=1 -DKALEIDOSCOPE_ENABLE_COVERAGE=1 -DKALEIDOSCOPE_ENABLE_CMD_TOOL=0 -S . -B build
      - name: Build
        run: cmake --build build --parallel --target coverage-xml
      - name: Process Results
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./build/coverage-xml.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
