name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: write  # for JamesIves/github-pages-deploy-action to push changes in repo
    runs-on: ubuntu-latest
    container: egecetinn/alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: "true"
      - name: Configure
        run: cmake . -DKALEIDOSCOPE_ENABLE_DOCS=1 -DKALEIDOSCOPE_ENABLE_CMD_TOOL=OFF
      - name: Generate Doxygen Documentation
        run: cmake --build . --target docs
      - name: Create .nojekyll (ensures pages with underscores work on gh pages)
        run: touch doc/html/.nojekyll
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: doc/html
