name: "MacOS"
on: [push, pull_request]

env:
  BUILD_DIR: build

jobs:
  linux:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -S . -B $BUILD_DIR
      - name: Build
        run: cmake --build $BUILD_DIR --parallel
      - name: Run Tests
        run: ctest --test-dir $BUILD_DIR
