name: "MacOS"
on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -DKALEIDOSCOPE_ENABLE_TESTS=ON -DKALEIDOSCOPE_ENABLE_CMD_TOOL=OFF -DKALEIDOSCOPE_ENABLE_PACKAGE=ON -S . -B build
      - name: Build
        run: cmake --build build --parallel --target package
      - name: Run Tests
        run: ctest --test-dir build
      - uses: actions/upload-artifact@v3
        with:
          path: build/dist/*
